[package]
name = "scorch-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "scorchd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
metasearch = { path = "../metasearch" }
scorch-api = { path = "../scorch-api" }
scorch-engine = { path = "../scorch-engine" }
scorch-types = { path = "../scorch-types" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
