mod bing;
mod brave;
mod brave_web;
mod catalogs;
mod crates_io;
mod crossref;
mod docker_hub;
mod duckduckgo;
mod github;
mod google;
mod google_cse;
mod hacker_news;
mod http;
mod mwmbl;
mod npm;
mod open_alex;
mod open_library;
mod pubmed;
mod wikidata;
mod wikipedia;
mod yahoo;

// Evaluated adapters intentionally excluded from the final binary surface:
// mod jisho;
// mod naver;
// mod pdbe;
// mod public_json;
// mod simple_json;
// mod stack_overflow;

pub use bing::Bing;
pub use brave::Brave;
pub use brave_web::BraveWeb;
pub use catalogs::{HuggingFace, Nvd};
pub use crates_io::CratesIo;
pub use crossref::Crossref;
pub use docker_hub::DockerHub;
pub use duckduckgo::DuckDuckGo;
pub use github::GitHub;
pub use google::Google;
pub use google_cse::GoogleCse;
pub use hacker_news::HackerNews;
pub use mwmbl::Mwmbl;
pub use npm::Npm;
pub use open_alex::OpenAlex;
pub use open_library::OpenLibrary;
pub use pubmed::PubMed;
pub use wikidata::Wikidata;
pub use wikipedia::Wikipedia;
pub use yahoo::Yahoo;
