[package]
name = "scorch-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chromiumoxide.workspace = true
dashmap.workspace = true
dom_smoothie.workspace = true
futures-util.workspace = true
html2md.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
robotstxt.workspace = true
scorch-types = { path = "../scorch-types" }
scraper.workspace = true
serde.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
